- hosts: webservers
  vars:
    - username: libreborme
  become: true

  tasks:
#  - name: Create {{ username }} user
#    user: name={{ username}} comment="LibreBORME" group=sudo

    # TODO: Idempotencia. http://docs.ansible.com/ansible/user_module.html
  - name: Create {{ username }} user
    command: useradd -m -G sudo -c "LibreBORME" -s /bin/bash {{ username }}

  - name: Install ssh key for {{ username }}
    authorized_key: user={{ username }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

