- hosts: webservers
  vars: 
    - venv_home: /home/vagrant/.virtualenvs/libreborme
    - www_dir: /var/www
    - lb_home: /home/vagrant/libreborme/
    - libreborme_dir: "{{ www_dir }}/libreborme"
    - project_name: mylibreborme
  become: True

  tasks:

  - name: create project folder
    file: dest={{ libreborme_dir }} state=directory owner=vagrant group=www-data mode=0775

  - name: create project {{ project_name }}
    shell:
      . {{ venv_home }}/bin/activate && cd {{ www_dir }} && libreborme startproject {{ project_name }} libreborme creates={{ libreborme_dir }}/manage.py

  - name: set permissions to project folder
    file: dest={{ libreborme_dir }} state=directory owner=vagrant group=www-data recurse=yes

  - name: set permissions to folders
    file: dest={{ libreborme_dir }}/{{item}} mode=0775
    with_items:
      - log
      - "{{ project_name }}/media"

  - name: set permissions to manage.py
    file: dest={{ libreborme_dir }}/manage.py mode=0750

  - name: Configuring piwik I
    lineinfile: dest={{ libreborme_dir }}/{{ project_name }}/settings.py regexp="^PIWIK_URL" line="PIWIK_URL = 'piwik.libreborme.net/'"

  - name: Configuring piwik II
    lineinfile: dest={{ libreborme_dir }}/{{ project_name }}/settings.py regexp="^PIWIK_SITE_ID" line="PIWIK_SITE_ID = '1'"

  - name: Disabling DEBUG mode
    lineinfile: dest={{ libreborme_dir }}/{{ project_name }}/settings.py regexp="^DEBUG" line="DEBUG = False"

  - name: Adding initial data to MongoDB
    command: 'mongo libreborme --eval "db.config.insert({last_modified: ''1970-01-01''})"'

  - name: Update libreborme version data
    shell: . {{ venv_home }}/bin/activate && {{ libreborme_dir }}/manage.py updateversion chdir={{ lb_home }}

  - name: Running sycdb, migrate and collecstatic
    shell:
      . {{ venv_home }}/bin/activate && cd {{ libreborme_dir }} && ./manage.py syncdb --no-initial-data --noinput && ./manage.py migrate --no-initial-data && ./manage.py collectstatic --noinput
