- hosts: libreborme
  vars: 
    - www_dir: /var/www
    - libreborme_dir: "{{ www_dir }}/libreborme"
    - project_name: mylibreborme

  tasks:

  - name: create project folder
    become: true
    file: dest={{ libreborme_dir }} state=directory owner=libreborme group=www-data mode=0775

  - name: create project folder
    shell:
      . /home/libreborme/Env/bin/activate && cd {{ www_dir }} && libreborme startproject {{ project_name }} libreborme creates={{ libreborme_dir }}/manage.py

  - name: set permissions to project folder
    become: true
    file: dest={{ libreborme_dir }} state=directory owner=libreborme group=www-data recurse=yes

  - name: set permissions to folders
    file: dest={{ libreborme_dir }}/{{item}} mode=0775
    with_items:
      - log
      - "{{ project_name }}/media"

  - name: set permissions to manage.py
    file: dest={{ libreborme_dir }}/manage.py mode=0750

  - name: Running sycdb, migrate and collecstatic
    shell:
      . /home/libreborme/Env/bin/activate && cd {{ libreborme_dir }} && ./manage.py syncdb --no-initial-data --noinput && ./manage.py migrate --no-initial-data && ./manage.py collectstatic --noinput
