- hosts: webservers
  vars: 
    - venv_home: /home/libreborme/.virtualenvs/libreborme
    - www_dir: /var/www
    - lb_home: /home/libreborme/libreborme/
    - libreborme_dir: "{{ www_dir }}/libreborme"
    - project_name: mylibreborme
  become: True

  tasks:

  - name: create project folder
    file: dest={{ libreborme_dir }} state=directory owner=libreborme group=www-data mode=0775

  - name: create project {{ project_name }}
    shell:
      . {{ venv_home }}/bin/activate && cd {{ www_dir }} && libreborme startproject {{ project_name }} libreborme creates={{ libreborme_dir }}/manage.py

  - name: set permissions to project folder
    file: dest={{ libreborme_dir }} state=directory owner=libreborme group=www-data recurse=yes

  - name: set permissions to folders
    file: dest={{ libreborme_dir }}/{{item}} mode=0775
    with_items:
      - log
      - "{{ project_name }}/media"

  - name: set permissions to manage.py
    file: dest={{ libreborme_dir }}/manage.py mode=0750

  - name: Configuring piwik I
    lineinfile: dest={{ libreborme_dir }}/{{ project_name }}/settings.py regexp="^PIWIK_URL" line="PIWIK_URL = 'piwik.libreborme.net/'"

  - name: Configuring piwik II
    lineinfile: dest={{ libreborme_dir }}/{{ project_name }}/settings.py regexp="^PIWIK_SITE_ID" line="PIWIK_SITE_ID = '1'"

  - name: Disabling DEBUG mode
    lineinfile: dest={{ libreborme_dir }}/{{ project_name }}/settings.py regexp="^DEBUG" line="DEBUG = False"

  - name: Create database
    postgresql_db: name=libreborme
    become_user: postgres

  - name: Create username for database libreborme
    postgresql_user: db=libreborme name=libreborme password=password priv=ALL
    become_user: postgres

  - name: Configure hstore extension in postgresql
    postgresql_ext: name=hstore db=libreborme
    become_user: postgres

  - name: Running migrate and collectstatic
    shell:
      . {{ venv_home }}/bin/activate && cd {{ libreborme_dir }} && ./manage.py migrate --no-initial-data && ./manage.py collectstatic --noinput
    become_user: libreborme

  - name: Update libreborme version data
    shell: . {{ venv_home }}/bin/activate && {{ libreborme_dir }}/manage.py updateversion chdir={{ lb_home }}
    become_user: libreborme

