- hosts: webservers
  vars:
    repository: https://github.com/PabloCastellano/libreborme.git
    repository_bp: https://github.com/PabloCastellano/bormeparser.git
    lb_home: /home/libreborme/libreborme/
    bp_home: /home/libreborme/bormeparser/
    venv_home: /home/libreborme/.virtualenvs/libreborme/
    www_dir: /var/www
    libreborme_dir: "{{ www_dir }}/libreborme"
    branch: develop

  tasks:

  - name: Update libreborme repository
    git: repo={{ repository }} dest={{ lb_home }} version={{ branch }}
    become: True
    become_user: libreborme

  - name: Update bormeparser repository
    git: repo={{ repository_bp }} dest={{ bp_home }}
    become: True
    become_user: libreborme

  - name: Update libreborme requirements
    pip: requirements={{ lb_home }}requirements/base.txt virtualenv={{ venv_home }}
    become: True
    become_user: libreborme

  - name: Update bormeparser requirements
    pip: requirements={{ bp_home }}requirements/python3.txt virtualenv={{ venv_home }}
    become: True
    become_user: libreborme

  # TODO: migrations?

  - name: Running django collectstatic
    django_manage: command="collectstatic --noinput" virtualenv={{ venv_home }} app_path={{ libreborme_dir }}
    become: True
    become_user: libreborme

  # BUG: https://github.com/ansible/ansible/issues/3977
  #- name: restart supervisor
  #  service: name=supervisor state=restarted

  - name: Restart uwsgi
    supervisorctl: name=uwsgi state=restarted

  #- name: Nginx service reload
  #  service: name=nginx state=reloaded
