- hosts: webservers
  vars:
    repository: https://github.com/PabloCastellano/libreborme.git
    repository_bp: https://github.com/PabloCastellano/bormeparser.git
    lb_home: /home/vagrant/libreborme/
    bp_home: /home/vagrant/bormeparser/
    venv_home: /home/vagrant/.virtualenvs/libreborme/
    branch: develop
  become: True

  tasks:

  - name: Update libreborme repository
    git: repo={{ repository }} dest={{ lb_home }} version={{ branch }}

  - name: Update bormeparser repository
    git: repo={{ repository_bp }} dest={{ bp_home }}

  - name: Update libreborme requirements
    pip: requirements={{ lb_home }}requirements/base.txt virtualenv={{ venv_home }}

  - name: Update bormeparser requirements
    pip: requirements={{ bp_home }}requirements/python3.txt virtualenv={{ venv_home }}

  # TODO: migrations?

  # BUG: https://github.com/ansible/ansible/issues/3977
  #- name: restart supervisor
  #  service: name=supervisor state=restarted

  - name: Restart uwsgi
    supervisorctl: name=uwsgi state=restarted

  #- name: Nginx service reload
  #  service: name=nginx state=reloaded
